// <auto-generated />
using System;
using CSharpRefactoringAssistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpRefactoringAssistant.Migrations
{
    [DbContext(typeof(RefactoringDbContext))]
    [Migration("20260227190221_AddTaskPlanEntities")]
    partial class AddTaskPlanEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.Checkpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DialogueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DialogueId");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.Dialogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DialogueGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DialogueGroupId");

                    b.ToTable("Dialogues");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.DialogueGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Design")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCollapsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tasks")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DialogueGroups");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.ExecutionSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentTask")
                        .HasColumnType("TEXT");

                    b.Property<int>("DialogueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Progress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SkipOptional")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TasksFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DialogueId");

                    b.ToTable("ExecutionSessions");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DialogueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DialogueId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.PlannedTaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoldersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskPlanId");

                    b.ToTable("PlannedTasks");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.SubTaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlannedTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlannedTaskId");

                    b.ToTable("SubTasks");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.TaskPlanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DialogueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DialogueId");

                    b.ToTable("TaskPlans");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.Checkpoint", b =>
                {
                    b.HasOne("CSharpRefactoringAssistant.Models.Dialogue", "Dialogue")
                        .WithMany("Checkpoints")
                        .HasForeignKey("DialogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialogue");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.Dialogue", b =>
                {
                    b.HasOne("CSharpRefactoringAssistant.Models.DialogueGroup", "DialogueGroup")
                        .WithMany("Dialogues")
                        .HasForeignKey("DialogueGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DialogueGroup");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.ExecutionSession", b =>
                {
                    b.HasOne("CSharpRefactoringAssistant.Models.Dialogue", "Dialogue")
                        .WithMany("ExecutionSessions")
                        .HasForeignKey("DialogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialogue");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.Message", b =>
                {
                    b.HasOne("CSharpRefactoringAssistant.Models.Dialogue", "Dialogue")
                        .WithMany("Messages")
                        .HasForeignKey("DialogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialogue");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.PlannedTaskEntity", b =>
                {
                    b.HasOne("CSharpRefactoringAssistant.Models.TaskPlanEntity", "TaskPlan")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskPlan");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.SubTaskEntity", b =>
                {
                    b.HasOne("CSharpRefactoringAssistant.Models.PlannedTaskEntity", "PlannedTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("PlannedTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlannedTask");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.TaskPlanEntity", b =>
                {
                    b.HasOne("CSharpRefactoringAssistant.Models.Dialogue", "Dialogue")
                        .WithMany()
                        .HasForeignKey("DialogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialogue");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.Dialogue", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("ExecutionSessions");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.DialogueGroup", b =>
                {
                    b.Navigation("Dialogues");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.PlannedTaskEntity", b =>
                {
                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("CSharpRefactoringAssistant.Models.TaskPlanEntity", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
