using System.Diagnostics;

namespace CSharpRefactoringAssistant.Services;

public class GitService : IGitService
{
    private readonly ILogger<GitService> _logger;

    public GitService(ILogger<GitService> logger)
    {
        _logger = logger;
    }

    public async Task<bool> IsGitRepositoryAsync(string path)
    {
        var gitDir = Path.Combine(path, ".git");
        return Directory.Exists(gitDir);
    }

    public async Task InitializeRepositoryAsync(string path)
    {
        // Execute: git init
        await ExecuteGitCommandAsync(path, "init");

        // Configure Git to not convert line endings
        await ExecuteGitCommandAsync(path, "config core.autocrlf false");
        await ExecuteGitCommandAsync(path, "config core.safecrlf false");

        // Create .gitignore for .NET
        var gitignorePath = Path.Combine(path, ".gitignore");
        await File.WriteAllTextAsync(gitignorePath, GetDotNetGitignore());

        // Execute: git add .gitignore
        await ExecuteGitCommandAsync(path, "add .gitignore");

        // Execute: git commit -m "Initial commit"
        await ExecuteGitCommandAsync(path, "commit -m \"Initial commit\"");
    }

    public async Task<string> CreateCheckpointAsync(string path, string message)
    {
        // Ensure Git is configured to not convert line endings
        try
        {
            await ExecuteGitCommandAsync(path, "config core.autocrlf false");
            await ExecuteGitCommandAsync(path, "config core.safecrlf false");
        }
        catch
        {
            // Ignore errors if config already set
        }

        // Check if there are any changes to commit
        var hasChanges = await HasUncommittedChangesAsync(path);
        
        if (!hasChanges)
        {
            // No changes to commit, return the current HEAD
            _logger.LogInformation("No changes to commit for checkpoint in {Path}", path);
            var currentHash = await ExecuteGitCommandAsync(path, "rev-parse HEAD");
            return currentHash.Trim();
        }

        // Execute: git add -A
        await ExecuteGitCommandAsync(path, "add -A");

        // Execute: git commit -m "{message}"
        await ExecuteGitCommandAsync(path, $"commit -m \"{message}\"");

        // Execute: git rev-parse HEAD
        var commitHash = await ExecuteGitCommandAsync(path, "rev-parse HEAD");
        return commitHash.Trim();
    }

    public async Task RollbackToCheckpointAsync(string path, string commitHash)
    {
        // Execute: git reset --hard {commitHash}
        await ExecuteGitCommandAsync(path, $"reset --hard {commitHash}");
    }

    public async Task<bool> HasUncommittedChangesAsync(string path)
    {
        // Execute: git status --porcelain
        var output = await ExecuteGitCommandAsync(path, "status --porcelain");
        return !string.IsNullOrWhiteSpace(output);
    }

    private async Task<string> ExecuteGitCommandAsync(string workingDirectory, string arguments)
    {
        _logger.LogDebug("Executing git command: git {Arguments} in {WorkingDirectory}", arguments, workingDirectory);

        var processStartInfo = new ProcessStartInfo
        {
            FileName = "git",
            Arguments = arguments,
            WorkingDirectory = workingDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        using var process = Process.Start(processStartInfo);
        if (process == null)
        {
            _logger.LogError("Failed to start git process");
            throw new GitException("Failed to start git process");
        }

        var output = await process.StandardOutput.ReadToEndAsync();
        var error = await process.StandardError.ReadToEndAsync();
        await process.WaitForExitAsync();

        if (process.ExitCode != 0)
        {
            var errorMessage = string.IsNullOrWhiteSpace(error) 
                ? $"Git command '{arguments}' failed with exit code {process.ExitCode}" 
                : error;
            _logger.LogError("Git command failed: {Error}", errorMessage);
            throw new GitException($"Git command failed: {errorMessage}");
        }

        _logger.LogDebug("Git command completed successfully");
        return output;
    }

    private string GetDotNetGitignore()
    {
        return @"
## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.suo
*.user
*.userosscache
*.sln.docstates

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Bb]in/
[Oo]bj/

# Visual Studio cache/options directory
.vs/

# SQLite database
*.db
*.db-shm
*.db-wal
";
    }
}

public class GitException : Exception
{
    public GitException(string message) : base(message) { }
}
